// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion():Promise<string>;

export function HTTPGetRequest(arg1:string):Promise<string>;

export function HandleError(arg1:Error):Promise<void>;

export function HandleErrorFrontend(arg1:string):Promise<void>;

export function LaunchLilith():Promise<string>;

export function LoadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function ShowDialog(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UpdateCheckUI():Promise<void>;
