// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HTTPGetRequest(arg1) {
  return window['go']['main']['App']['HTTPGetRequest'](arg1);
}

export function HandleError(arg1) {
  return window['go']['main']['App']['HandleError'](arg1);
}

export function HandleErrorFrontend(arg1) {
  return window['go']['main']['App']['HandleErrorFrontend'](arg1);
}

export function LaunchLilith() {
  return window['go']['main']['App']['LaunchLilith']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowDialog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ShowDialog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateCheckUI() {
  return window['go']['main']['App']['UpdateCheckUI']();
}
